# USER OPERATIONS

# Obtener los detalles del usuario autenticado
GET http://localhost:3001/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJkaWVnb21hemFzY3VyaWVsQGdtYWlsLmNvbSIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3MzMwMTAzMDMsImV4cCI6MTczMzAxMzkwM30.5qWJWrn7rSIqGZH0XifQJUwGzQapGl8vTVVs1ohKe-c
Content-Type: application/json

###