# PASSWORD RESET OPERATIONS

# Solicitar recuperación de contraseña para un cliente
POST http://localhost:3001/api/password/request-reset
Content-Type: application/json

{
    "email": "tayet.nunez@gmail.com"
}

###

# Solicitar recuperación de contraseña para un administrador
POST http://localhost:3001/api/password/request-reset
Content-Type: application/json

{
    "email": "admin.user@gmail.com"
}

###

# Solicitar recuperación de contraseña para un profesor
POST http://localhost:3001/api/password/request-reset
Content-Type: application/json

{
    "email": "teacher.user@gmail.com"
}

###

# Actualizar la contraseña utilizando el token de recuperación
POST http://localhost:3001/api/password/reset
Content-Type: application/json

{
    "token": "el_token_de_recuperacion",
    "password": "nueva_contraseña"
}