# PASSWORD RESET OPERATIONS

# Solicitar recuperación de contraseña para un cliente
POST http://localhost:3001/api/password/request-reset
Content-Type: application/json

{
    "email": "tayet.nunez@gmail.com",
    "role": "client"
}

###

# Solicitar recuperación de contraseña para un administrador
POST http://localhost:3001/api/password/request-reset
Content-Type: application/json

{
    "email": "admin.user@gmail.com",
    "role": "administrator"
}

###

# Solicitar recuperación de contraseña para un profesor
POST http://localhost:3001/api/password/request-reset
Content-Type: application/json

{
    "email": "teacher.user@gmail.com",
    "role": "teacher"
}

###

# Actualizar la contraseña utilizando el token de recuperación
POST http://localhost:3001/api/password/reset
Content-Type: application/json

{
    "token": "366d069833ac6d780cf49024328b93346e40a0fda39110761df09cfe78c8f8ed",
    "password": "NuevaContraseña123",
    "role": "client"
}