# Obtener todos los usuarios
GET http://localhost:3001/api/clients
Content-Type: application/json

###

# Crear un nuevo usuario
POST http://localhost:3001/api/clients
Content-Type: application/json

{
    "name": "Diego Alejandro",
    "email": "diego.mazas@gmail.com",
    "password": "contraseña"
}
