# Agregar un producto a los favoritos
POST http://localhost:3001/api/favorites
Content-Type: application/json

{
  "userId": 1,
  "productId": 12
}

###

# Obtener todos los favoritos de un usuario
GET http://localhost:3001/api/favorites/1