# ADMINISTRATOR OPERATIONS

# Obtener todos los administradores
GET http://localhost:3001/api/administrators
Content-Type: application/json

###

# Obtener un administrador por email
GET http://localhost:3001/api/administrators/admin.user@gmail.com
Content-Type: application/json

###

# Crear un nuevo administrador
POST http://20.124.162.43:3001/api/administrators
Content-Type: application/json

{
    "name": "Admin2",
    "email": "admin2@gmail.com",
    "password": "Admin123"
}

###

# Actualizar un administrador
PUT http://localhost:3001/api/administrators/1
Content-Type: application/json

{
    "name": "Admin User Updated",
    "email": "admin.user.updated@gmail.com"
}

###

# Eliminar un administrador
DELETE http://localhost:3001/api/administrators/4
Content-Type: application/json