# Crear un nuevo producto con imagen
POST http://localhost:3001/api/products
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="product"
Content-Type: application/json

{
    "name": "Nuevo Producto",
    "description": "Descripción del nuevo producto",
    "price": 100,
    "stock": 50,
    "categoryId": 1
}
--boundary
Content-Disposition: form-data; name="image"; filename="images.jpg"
Content-Type: image/jpeg

< D:/Descargas/tiferet-images/images.jpg
--boundary--