# PRODUCT OPERATIONS

# Obtener todos los productos
GET http://localhost:3001/api/products
Content-Type: application/json

###

# Crear un nuevo producto
POST http://localhost:3001/api/products
Content-Type: application/json

{
    "name": "Smartphone",
    "description": "Latest model smartphone",
    "price": 699,
    "stock": 50,
    "category_id": 2
}

###

# Actualizar un producto
PUT http://localhost:3001/api/products/2
Content-Type: application/json

{
    "name": "Updated Smartphone",
    "description": "Updated description for smartphone",
    "price": 749,
    "stock": 45,
    "category_id": 2
}

###

# Eliminar un producto
DELETE http://localhost:3001/api/products/2
Content-Type: application/json